version: "3.9"
services:
  stock-exchange-service:
    image: local.stock_exchange
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:6.2.6-alpine
