# Generated by Django 4.2.4 on 2023-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("high", models.DecimalField(decimal_places=4, max_digits=10)),
                ("low", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "change_price_percent",
                    models.DecimalField(
                        decimal_places=4, help_text="Change in percentage", max_digits=5
                    ),
                ),
            ],
        ),
    ]
